# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Install Dfx
  - init: sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
    command: echo 'y'

  - name: Install Packages
  - init: npm install


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
