image:
  file: .gitpod.Dockerfile
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: environment startup
  - before: echo "export PATH=/home/gitpod/bin/:$PATH" > ~/.bashrc && source ~/.bashrc
    init: |
      dfx start --background
      dfx deploy hello
      npm install
    command: |
      npm start

  - name: open app
    command: gp open src/hello_assets/src/App.jsx
  - command: zsh

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
  - port: 8000
    onOpen: ignore
vscode:
  extensions:
  - esbenp.prettier-vscode
  - coenraads.bracket-pair-colorizer-2
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false