image:
  file: .gitpod.Dockerfile
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: environment startup
  - before: echo "export PATH=/home/gitpod/bin/:$PATH" > ~/.bashrc && source ~/.bashrc
    init: |
      dfx start --background
      dfx deploy hello
      npm install
    command: |
      npm start

  - name: open app
    command: gp open src/hello_assets/src/App.jsx

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: notify
  - port: 8000
    onOpen: ignore
vscode:
  extensions:
  - esbenp.prettier-vscode
  - coenraads.bracket-pair-colorizer-2
