image:
  file: .gitpod.Dockerfile
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: npm install
    command: |
      echo "export PATH=/home/gitpod/bin/:$PATH" > ~/.bashrc
      "source ~/.bashrc"
      dfx start --background
      dfx deploy test
      npm start
  - command: /home/gitpod/bin/dfx start --background
    name: replica
    openMode: tab-after

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
vscode:
  extensions:
  - esbenp.prettier-vscode
  - coenraads.bracket-pair-colorizer-2
