image:
  file: .gitpod.Dockerfile
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: npm startup
  - init: npm install
    command: |
      npm install
      npm start

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8000
    onOpen: ignore
  - port: 3000
    onOpen: notify
vscode:
  extensions:
  - esbenp.prettier-vscode
  - coenraads.bracket-pair-colorizer-2
